-- function set_background(content)
--   osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/Users/Brandon/Pictures/background-images/\"' .. content ..'\""'
-- end
--
-- set_background("zelda.jpeg")
