#!/bin/bash
# JankyBorders color configuration — generated by ricekit
# Install: brew install FelixKratz/formulae/borders

# Convert #RRGGBB to 0xffRRGGBB (ARGB format)
hex() { echo "0xff${1:1}"; }

# Linear gradient on the active border: accent -> foreground (TL -> BR)
ACTIVE_COLOR="gradient(top_left=$(hex "{{accent}}"),bottom_right=$(hex "{{foreground}}"))"
INACTIVE_COLOR=$(hex "{{border}}")
BORDER_WIDTH="5.0"
# Uniform corner radius for all borders — macOS Tahoe gives WezTerm's
# titlebar-less (RESIZE) window a larger system corner radius than normal
# titled windows; "uniform" draws every border at the same radius instead
# of hugging each window's reported radius.
BORDER_STYLE="uniform"

# Restart borders with new colors
pkill -x borders 2>/dev/null || true
sleep 0.2

BORDERS_BIN=""
if [ -x "/opt/homebrew/bin/borders" ]; then
  BORDERS_BIN="/opt/homebrew/bin/borders"
elif [ -x "/usr/local/bin/borders" ]; then
  BORDERS_BIN="/usr/local/bin/borders"
elif command -v borders >/dev/null 2>&1; then
  BORDERS_BIN="borders"
fi

if [ -n "$BORDERS_BIN" ]; then
  nohup "$BORDERS_BIN" \
    active_color="$ACTIVE_COLOR" \
    inactive_color="$INACTIVE_COLOR" \
    width="$BORDER_WIDTH" \
    style="$BORDER_STYLE" \
    >/dev/null 2>&1 &
  disown
fi
